server:
  port: 9000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_registration?useUnicode=yes&amp;characterEncoding=UTF-8
    username: postgres
    password: 100293064
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: create
      ddl-auto: update
    database: postgresql
